version: '3.3'

volumes:
    db_foodgram:
    static:
    media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_foodgram:/var/lib/postgresql/data

  backend:
    build: ./backend/foodgram
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/frontend/
    volumes:
      - static:/frontend_static/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/nginx.bak.conf:/etc/nginx/templates/default.conf.template
#      - nginx.bak.conf /etc/nginx/templates/default.conf.template
#      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/var/html/api/docs/
#      - static:/var/html/static/
#      - media:/var/html/media/
    depends_on:
      - db
      - frontend
      - backend

networks:
  foodgram:
