# Generated by Django 3.2.19 on 2024-07-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Subscriptions',
        ),
    ]
